version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: notasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db-data:
