version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notasdb
    volumes:                # ← estaba mal indentado aquí
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db-data:
